name: My CI Workflow

on: push

jobs:
  some-docker-thing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check external image cache
        id: cache-images
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-images-${{ runner.os }}

      - name: Load cached images if available
        if: steps.cache-images.outputs.cache-hit == 'true'
        run: docker load -i /tmp/docker-cache/docker-images.tar || true

      - name: Pull and cache external images if needed
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/docker-cache
          docker compose pull
          docker save  $(docker images -q) -o /tmp/docker-cache/docker-images.tar

      - name: Save external images to cache
        if: steps.cache-images.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-images-${{ runner.os }}

      - name: Build, cache or push internal Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Run the app
        run: docker compose run app